# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    assignees:
      - tshion

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    assignees:
      - tshion
    ignore:
      # res/.node-version の設定に合わせるため
      - dependency-name: "@types/node"
        versions: [">=21.0.0"]
      # CommonJS のため
      - dependency-name: "node-fetch"
        versions: [">=3.0.0"]
