name: Create a release pull request

on:
  workflow_dispatch:
    inputs:
      versionBuild:
        description: 'バージョン情報: build(1桁)'
        required: true
        default: 0
        type: number

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-pr:
    if: ${{ 0 <= inputs.versionBuild && inputs.versionBuild < 10 && github.ref_type == 'branch' && github.ref_name == 'develop' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v6

      - name: Format meta data
        id: meta
        env:
          BUILD: ${{ inputs.versionBuild }}
        run: |
          version="$(bash .github/scripts/date.bash)${BUILD}"
          echo "branch=feature/${version}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      # https://github.com/tshion/can-create-release
      - uses: tshion/can-create-release@0.1.2
        with:
          tag: ${{ steps.meta.outputs.version }}

      # https://github.com/tshion/apply-git-user
      - uses: tshion/apply-git-user@2.1.2
        with:
          user: github-actions

      - name: Create a working git branch
        env:
          BRANCH: ${{ steps.meta.outputs.branch }}
        run: |
          git switch --create "$BRANCH"
          git fetch origin released
          git merge --allow-unrelated-histories --strategy=ours origin/released

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - run: npm ci

      - run: npm run configuration

      - name: Check code style
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Set version
        env:
          VERSION: ${{ steps.meta.outputs.version }}
        run: bash .github/scripts/set-version.bash "$VERSION"

      - name: git commit & push
        env:
          BRANCH: ${{ steps.meta.outputs.branch }}
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          git add package.json
          git add package-lock.json
          git commit --message "Update $VERSION"
          git push --set-upstream origin "$BRANCH"

      - name: Generate diff notes
        id: notes
        env:
          GH_TOKEN: ${{ github.token }}
          REF_NAME: ${{ steps.meta.outputs.branch }}
          REPO: ${{ github.repository }}
        run: |
          response=$(bash .github/scripts/presume-release-notes.bash "$REPO" "$REF_NAME")
          echo "response=$response" >> "$GITHUB_OUTPUT"

      - name: Create a file for pull request body
        env:
          FILENAME: PR_BODY
          NOTE: ${{ fromJson(steps.notes.outputs.response).body }}
        run: node .github/scripts/create-release-pr-body.js "$FILENAME" "$NOTE"

      - name: Create pull request
        env:
          BASE: released
          FILENAME: PR_BODY
          GH_TOKEN: ${{ github.token }}
          REVIEWER: tshion
          VERSION: ${{ steps.meta.outputs.version }}
        run: gh pr create --base "$BASE" --reviewer "$REVIEWER" --title "Update $VERSION" --body-file "$FILENAME"
