name: Create a release pull request

on:
  workflow_dispatch:
    inputs:
      osRunner:
        default: ubuntu-24.04
        description: https://github.com/actions/runner-images
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'develop' }}
    runs-on: ${{ inputs.osRunner }}
    outputs:
      version: ${{ steps.meta.outputs.version }}
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Format meta data
        id: meta
        run: |
          date=$(bash .github/scripts/date.bash)
          echo "version=$date" >> "$GITHUB_OUTPUT"

      # https://github.com/tshion/can-create-release
      - uses: tshion/can-create-release@0.1.1
        with:
          tag: ${{ steps.meta.outputs.version }}

  create-pr:
    needs:
      - check
    runs-on: ${{ inputs.osRunner }}
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 3
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Set version
        env:
          VERSION: ${{ needs.check.outputs.version }}
        run: bash .github/scripts/set-version.bash "$VERSION"

      - name: Generate diff notes
        id: notes
        env:
          GH_TOKEN: ${{ github.token }}
          REF_NAME: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
        run: |
          response=$(bash .github/scripts/presume-release-notes.bash "$REPO" "$REF_NAME")
          echo "response=$response" >> "$GITHUB_OUTPUT"

      - name: Create a file for pull request body
        shell: ruby {0}
        env:
          NOTE: ${{ fromJson(steps.notes.outputs.response).body }}
        run: |
          text = <<"BODY"
            #{ENV['NOTE']}
          BODY
          File.open("PR_BODY", "w") { |file|
            file.write(text)
          }

      # https://github.com/tshion/apply-git-user
      - uses: tshion/apply-git-user@2.1.1
        with:
          user: github-actions

      - name: git add & push
        env:
          VERSION: ${{ needs.check.outputs.version }}
        run: |
          branch="feature/$VERSION"

          git switch --create "$branch"
          git add package.json
          git add package-lock.json
          git commit --message "Update $VERSION"
          git push --set-upstream origin "$branch"

      - name: Create pull request
        env:
          ASSIGNEE: tshion
          BASE: released
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ needs.check.outputs.version }}
        run: gh pr create --assignee "$ASSIGNEE" --base "$BASE" --title "Update $VERSION" --body-file PR_BODY
