name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - released
    paths:
      - package.json
      - package-lock.json

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  preparation:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Get version name
        id: meta
        run: |
          version=$(bash .github/scripts/get-version.bash)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - run: npm ci

      - run: npm run deploy

      - name: Zip files
        id: zip
        working-directory: build
        env:
          ZIP_NAME: 'mkcmd_${{ steps.meta.outputs.version }}.zip'
        run: |
          zip -X -r "$ZIP_NAME" .
          echo "name=$ZIP_NAME" >> "$GITHUB_OUTPUT"

      - name: Create release notes
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.meta.outputs.version }}
          ZIP_PATH: 'build/${{ steps.zip.outputs.name }}'
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"
          gh release create "$VERSION" "$ZIP_PATH" --generate-notes --title "$VERSION"
