name: Test git operation

on:
  workflow_dispatch:
    inputs:
      osRunner:
        default: ubuntu-24.04
        description: https://github.com/actions/runner-images
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'develop' }}
    runs-on: ${{ inputs.osRunner }}
    timeout-minutes: 5
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Show git branches
        run: git branch

      - name: Checkout git branch
        run: |
          git fetch origin released
          git checkout released

      - name: Show git branches
        run: git branch

      - name: Create a git branch
        run: git switch --create test/branch

      - name: Show git branches
        run: git branch
